spring:
  application:
    name: agendamento-medico
  datasource:
    url: jdbc:h2:mem:testdb
    driver:
      driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  security:
    filter-dispatcher-types: ASYNC, ERROR, REQUEST
    web:
      security:
        ignored: /swagger-ui/**,/v3/api-docs/**  # Ignora o Swagger para autenticação

springdoc:
  api-docs:
    enabled: true  # Habilita a geração da documentação OpenAPI
    path: /v3/api-docs  # URL para acessar os docs JSON
  swagger-ui:
    enabled: true  # Habilita a interface do Swagger UI
    path: /swagger-ui.html  # URL para acessar a UI do Swagger
    operations-sorter: method  # Ordena os endpoints por método HTTP
    tags-sorter: alpha  # Ordena os grupos de endpoints em ordem alfabética


